modeset : modeset.c
	gcc -o modeset modeset.c -I/usr/include/drm -ldrm -g

testDrm : testDrm.cpp
	g++ -o testDrm testDrm.cpp
printModes : printModes.c
	gcc -o printModes printModes.c -I/usr/include/drm -ldrm -g
